### ISSUE TITLE
Rackspace SDK is not compatible with UAP,Version=v10.0 (win10-x64-aot).

### ISSUE THREAD

**Issue by LeoVernaza** [rackspace/rackspace-net-sdk#38]
I can not install Rackspace SDK by NuGet, because I have an error "not compatible with UAP,Version=v10.0 (win 10-x64-aot)."
My project is wrote in c# as a universal windows (Universal Windows Platform) I'm using Visual Studio 2015.
![capture](https://cloud.githubusercontent.com/assets/7053776/9498769/2f84916a-4be1-11e5-9a62-09140ebc548b.PNG)

**Comment by carolynvs** [comment]
Unfortunately the Rackspace .NET SDK doesn't support Universal Windows Platform. This is something that we are targeting in the future once we get our dependencies, such as OpenStack.NET, building for UWP as well.

I am closing this issue and you may subscribe to #39 to track our progress.
